apiVersion: v1
kind: PersistentVolume
metadata:
  name: registry-pv
  labels:
    cpp: registry
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/data/registry
