apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  ports:
    - port: 80
      nodePort: 30003
      name: http
    - port: 443
      nodePort: 30004
      name: https
    - port: 22
      nodePort: 30005
      name: ssh 
  selector:
    app: gitlab
    tier: gitlab
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        tier: gitlab
    spec:
      containers:
      - image: gitlab/gitlab-ce:latest
        name: gitlab
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        - containerPort: 22
          name: ssh
        volumeMounts:
        - name: config
          mountPath: /etc/gitlab
        - name: logs
          mountPath: /var/log/gitlab
        - name: data
          mountPath: /var/opt/gitlab
      volumes:
      - name: config
        hostPath:
          path: /tmp/data/gitlab/config
      - name: logs
        hostPath:
          path: /tmp/data/gitlab/logs
      - name: data
        hostPath:
          path: /tmp/data/gitlab/data
